import type { KeygroupHeader } from '@audiocontrol/sampler-devices/s3k';

/**
 * Build a complete KeygroupHeader with safe defaults for all fields.
 * Pass overrides for only the fields relevant to your test.
 */
export function makeKeygroupHeader(
  overrides: Partial<KeygroupHeader> = {},
): KeygroupHeader {
  const defaults: KeygroupHeader = {
    KGIDENT: 2, KGIDENTLabel: '',
    NXTKG: 0, NXTKGLabel: '',
    LONOTE: 21, LONOTELabel: '',
    HINOTE: 127, HINOTELabel: '',
    KGTUNO: 0, KGTUNOLabel: '',
    FILFRQ: 0, FILFRQLabel: '',
    K_FREQ: 0, K_FREQLabel: '',
    V_FREQ: 0, V_FREQLabel: '',
    P_FREQ: 0, P_FREQLabel: '',
    E_FREQ: 0, E_FREQLabel: '',
    ATTAK1: 0, ATTAK1Label: '',
    DECAY1: 0, DECAY1Label: '',
    SUSTN1: 0, SUSTN1Label: '',
    RELSE1: 0, RELSE1Label: '',
    V_ATT1: 0, V_ATT1Label: '',
    V_REL1: 0, V_REL1Label: '',
    O_REL1: 0, O_REL1Label: '',
    K_DAR1: 0, K_DAR1Label: '',
    ENV2R1: 0, ENV2R1Label: '',
    ENV2R3: 0, ENV2R3Label: '',
    ENV2L3: 0, ENV2L3Label: '',
    ENV2R4: 0, ENV2R4Label: '',
    V_ATT2: 0, V_ATT2Label: '',
    V_REL2: 0, V_REL2Label: '',
    O_REL2: 0, O_REL2Label: '',
    K_DAR2: 0, K_DAR2Label: '',
    V_ENV2: 0, V_ENV2Label: '',
    E_PTCH: 0, E_PTCHLabel: '',
    VXFADE: 0, VXFADELabel: '',
    VZONES: 0, VZONESLabel: '',
    LKXF: 0, LKXFLabel: '',
    RKXF: 0, RKXFLabel: '',
    // Velocity zone 1
    SNAME1: '            ', SNAME1Label: '',
    LOVEL1: 0, LOVEL1Label: '',
    HIVEL1: 127, HIVEL1Label: '',
    VTUNO1: 0, VTUNO1Label: '',
    VLOUD1: 0, VLOUD1Label: '',
    VFREQ1: 0, VFREQ1Label: '',
    VPANO1: 0, VPANO1Label: '',
    ZPLAY1: 0, ZPLAY1Label: '',
    LVXF1: 0, LVXF1Label: '',
    HVXF1: 0, HVXF1Label: '',
    SBADD1: 0, SBADD1Label: '',
    // Velocity zone 2
    SNAME2: '            ', SNAME2Label: '',
    LOVEL2: 0, LOVEL2Label: '',
    HIVEL2: 127, HIVEL2Label: '',
    VTUNO2: 0, VTUNO2Label: '',
    VLOUD2: 0, VLOUD2Label: '',
    VFREQ2: 0, VFREQ2Label: '',
    VPANO2: 0, VPANO2Label: '',
    ZPLAY2: 0, ZPLAY2Label: '',
    LVXF2: 0, LVXF2Label: '',
    HVXF2: 0, HVXF2Label: '',
    SBADD2: 0, SBADD2Label: '',
    // Velocity zone 3
    SNAME3: '            ', SNAME3Label: '',
    LOVEL3: 0, LOVEL3Label: '',
    HIVEL3: 127, HIVEL3Label: '',
    VTUNO3: 0, VTUNO3Label: '',
    VLOUD3: 0, VLOUD3Label: '',
    VFREQ3: 0, VFREQ3Label: '',
    VPANO3: 0, VPANO3Label: '',
    ZPLAY3: 0, ZPLAY3Label: '',
    LVXF3: 0, LVXF3Label: '',
    HVXF3: 0, HVXF3Label: '',
    SBADD3: 0, SBADD3Label: '',
    // Velocity zone 4
    SNAME4: '            ', SNAME4Label: '',
    LOVEL4: 0, LOVEL4Label: '',
    HIVEL4: 127, HIVEL4Label: '',
    VTUNO4: 0, VTUNO4Label: '',
    VLOUD4: 0, VLOUD4Label: '',
    VFREQ4: 0, VFREQ4Label: '',
    VPANO4: 0, VPANO4Label: '',
    ZPLAY4: 0, ZPLAY4Label: '',
    LVXF4: 0, LVXF4Label: '',
    HVXF4: 0, HVXF4Label: '',
    SBADD4: 0, SBADD4Label: '',
    // Miscellaneous
    KBEAT: 0, KBEATLabel: '',
    AHOLD: 0, AHOLDLabel: '',
    CP1: 0, CP1Label: '',
    CP2: 0, CP2Label: '',
    CP3: 0, CP3Label: '',
    CP4: 0, CP4Label: '',
    VZOUT1: 0, VZOUT1Label: '',
    VZOUT2: 0, VZOUT2Label: '',
    VZOUT3: 0, VZOUT3Label: '',
    VZOUT4: 0, VZOUT4Label: '',
    VSS1: 0, VSS1Label: '',
    VSS2: 0, VSS2Label: '',
    VSS3: 0, VSS3Label: '',
    VSS4: 0, VSS4Label: '',
    KV_LO: 0, KV_LOLabel: '',
    FILQ: 0, FILQLabel: '',
    // Modulation and filter control
    L_PTCH: 0, L_PTCHLabel: '',
    MODVFILT1: 0, MODVFILT1Label: '',
    MODVFILT2: 0, MODVFILT2Label: '',
    MODVFILT3: 0, MODVFILT3Label: '',
    MODVPITCH: 0, MODVPITCHLabel: '',
    MODVAMP3: 0, MODVAMP3Label: '',
    // Envelope 2 additional
    ENV2L1: 0, ENV2L1Label: '',
    ENV2R2: 0, ENV2R2Label: '',
    ENV2L2: 0, ENV2L2Label: '',
    ENV2L4: 0, ENV2L4Label: '',
    // Mute group and effects
    KGMUTE: 0, KGMUTELabel: '',
    PFXCHAN: 0, PFXCHANLabel: '',
    PFXSLEV: 0, PFXSLEVLabel: '',
    Reserved_1: 0, Reserved_1Label: '',
    // Second filter
    LSI2_ON: 0, LSI2_ONLabel: '',
    FLT2GAIN: 0, FLT2GAINLabel: '',
    FLT2MODE: 0, FLT2MODELabel: '',
    FLT2Q: 0, FLT2QLabel: '',
    TONEFREQ: 0, TONEFREQLabel: '',
    TONESLOP: 0, TONESLOPLabel: '',
    MODVFLT2_1: 0, MODVFLT2_1Label: '',
    MODVFLT2_2: 0, MODVFLT2_2Label: '',
    MODVFLT2_3: 0, MODVFLT2_3Label: '',
    FIL2FR: 0, FIL2FRLabel: '',
    K_FRQ2: 0, K_FRQ2Label: '',
    // Envelope 3
    ATTAK3: 0, ATTAK3Label: '',
    ENV3L1: 0, ENV3L1Label: '',
    ENV3R2: 0, ENV3R2Label: '',
    ENV3L2: 0, ENV3L2Label: '',
    ENV3R3: 0, ENV3R3Label: '',
    ENV3L3: 0, ENV3L3Label: '',
    ENV3R4: 0, ENV3R4Label: '',
    ENV3L4: 0, ENV3L4Label: '',
    V_ATT3: 0, V_ATT3Label: '',
    V_REL3: 0, V_REL3Label: '',
    O_REL3: 0, O_REL3Label: '',
    K_DAR3: 0, K_DAR3Label: '',
    V_ENV3: 0, V_ENV3Label: '',
    // Keygroup effects override
    KFXCHAN: 0, KFXCHANLabel: '',
    KFXSLEV: 0, KFXSLEVLabel: '',
    raw: [],
  };

  return { ...defaults, ...overrides };
}
