import type { KeygroupHeader } from '@audiocontrol/sampler-devices/s3k';
import type { FieldSpec } from '@/node/lib/field-specs-program.js';

export const KEYGROUP_FIELD_SPECS: FieldSpec<KeygroupHeader>[] = [
  {
    field: 'KGIDENT',
    type: 'number',
    writeFn: 'KeygroupHeader_writeKGIDENT',
    read: (h) => h.KGIDENT,
    testValue: 0,
    skip: 'Block identifier, must equal 2',
  },
  {
    field: 'NXTKG',
    type: 'number',
    writeFn: 'KeygroupHeader_writeNXTKG',
    read: (h) => h.NXTKG,
    testValue: 0,
    skip: 'Internal next keygroup address',
  },
  {
    field: 'LONOTE',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLONOTE',
    read: (h) => h.LONOTE,
    testValue: 36,
  },
  {
    field: 'HINOTE',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHINOTE',
    read: (h) => h.HINOTE,
    testValue: 96,
  },
  {
    field: 'KGTUNO',
    type: 'number',
    writeFn: 'KeygroupHeader_writeKGTUNO',
    read: (h) => h.KGTUNO,
    testValue: 10,
  },
  {
    field: 'FILFRQ',
    type: 'number',
    writeFn: 'KeygroupHeader_writeFILFRQ',
    read: (h) => h.FILFRQ,
    testValue: 50,
  },
  {
    field: 'K_FREQ',
    type: 'number',
    writeFn: 'KeygroupHeader_writeK_FREQ',
    read: (h) => h.K_FREQ,
    testValue: 25,
  },
  {
    field: 'V_FREQ',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_FREQ',
    read: (h) => h.V_FREQ,
    testValue: 15,
  },
  {
    field: 'P_FREQ',
    type: 'number',
    writeFn: 'KeygroupHeader_writeP_FREQ',
    read: (h) => h.P_FREQ,
    testValue: 10,
  },
  {
    field: 'E_FREQ',
    type: 'number',
    writeFn: 'KeygroupHeader_writeE_FREQ',
    read: (h) => h.E_FREQ,
    testValue: 20,
  },
  {
    field: 'ATTAK1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeATTAK1',
    read: (h) => h.ATTAK1,
    testValue: 30,
  },
  {
    field: 'DECAY1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeDECAY1',
    read: (h) => h.DECAY1,
    testValue: 40,
  },
  {
    field: 'SUSTN1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeSUSTN1',
    read: (h) => h.SUSTN1,
    testValue: 60,
  },
  {
    field: 'RELSE1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeRELSE1',
    read: (h) => h.RELSE1,
    testValue: 25,
  },
  {
    field: 'V_ATT1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_ATT1',
    read: (h) => h.V_ATT1,
    testValue: 15,
  },
  {
    field: 'V_REL1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_REL1',
    read: (h) => h.V_REL1,
    testValue: 10,
  },
  {
    field: 'O_REL1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeO_REL1',
    read: (h) => h.O_REL1,
    testValue: 5,
  },
  {
    field: 'K_DAR1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeK_DAR1',
    read: (h) => h.K_DAR1,
    testValue: 10,
  },
  {
    field: 'ENV2R1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV2R1',
    read: (h) => h.ENV2R1,
    testValue: 30,
  },
  {
    field: 'ENV2R3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV2R3',
    read: (h) => h.ENV2R3,
    testValue: 20,
  },
  {
    field: 'ENV2L3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV2L3',
    read: (h) => h.ENV2L3,
    testValue: 50,
  },
  {
    field: 'ENV2R4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV2R4',
    read: (h) => h.ENV2R4,
    testValue: 15,
  },
  {
    field: 'V_ATT2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_ATT2',
    read: (h) => h.V_ATT2,
    testValue: 12,
  },
  {
    field: 'V_REL2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_REL2',
    read: (h) => h.V_REL2,
    testValue: 8,
  },
  {
    field: 'O_REL2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeO_REL2',
    read: (h) => h.O_REL2,
    testValue: 5,
  },
  {
    field: 'K_DAR2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeK_DAR2',
    read: (h) => h.K_DAR2,
    testValue: 10,
  },
  {
    field: 'V_ENV2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_ENV2',
    read: (h) => h.V_ENV2,
    testValue: 20,
  },
  {
    field: 'E_PTCH',
    type: 'number',
    writeFn: 'KeygroupHeader_writeE_PTCH',
    read: (h) => h.E_PTCH,
    testValue: 5,
  },
  {
    field: 'VXFADE',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVXFADE',
    read: (h) => h.VXFADE,
    testValue: 1,
  },
  {
    field: 'VZONES',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVZONES',
    read: (h) => h.VZONES,
    testValue: 2,
  },
  {
    field: 'LKXF',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLKXF',
    read: (h) => h.LKXF,
    testValue: 0,
    skip: 'Internal crossfade factor',
  },
  {
    field: 'RKXF',
    type: 'number',
    writeFn: 'KeygroupHeader_writeRKXF',
    read: (h) => h.RKXF,
    testValue: 0,
    skip: 'Internal crossfade factor',
  },
  // --- Zone 1 ---
  {
    field: 'SNAME1',
    type: 'string',
    writeFn: 'KeygroupHeader_writeSNAME1',
    read: (h) => h.SNAME1,
    testValue: 'FIELDTEST1  ',
  },
  {
    field: 'LOVEL1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLOVEL1',
    read: (h) => h.LOVEL1,
    testValue: 0,
  },
  {
    field: 'HIVEL1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHIVEL1',
    read: (h) => h.HIVEL1,
    testValue: 127,
  },
  {
    field: 'VTUNO1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVTUNO1',
    read: (h) => h.VTUNO1,
    testValue: 5,
  },
  {
    field: 'VLOUD1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVLOUD1',
    read: (h) => h.VLOUD1,
    testValue: 10,
  },
  {
    field: 'VFREQ1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVFREQ1',
    read: (h) => h.VFREQ1,
    testValue: 5,
  },
  {
    field: 'VPANO1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVPANO1',
    read: (h) => h.VPANO1,
    testValue: 15,
  },
  {
    field: 'ZPLAY1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeZPLAY1',
    read: (h) => h.ZPLAY1,
    testValue: 2,
  },
  {
    field: 'LVXF1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLVXF1',
    read: (h) => h.LVXF1,
    testValue: 0,
    skip: 'Internal velocity crossfade',
  },
  {
    field: 'HVXF1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHVXF1',
    read: (h) => h.HVXF1,
    testValue: 0,
    skip: 'Internal velocity crossfade',
  },
  {
    field: 'SBADD1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeSBADD1',
    read: (h) => h.SBADD1,
    testValue: 0,
    skip: 'Internal sample block address',
  },
  // --- Zone 2 ---
  {
    field: 'SNAME2',
    type: 'string',
    writeFn: 'KeygroupHeader_writeSNAME2',
    read: (h) => h.SNAME2,
    testValue: 'FIELDTEST2  ',
  },
  {
    field: 'LOVEL2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLOVEL2',
    read: (h) => h.LOVEL2,
    testValue: 0,
  },
  {
    field: 'HIVEL2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHIVEL2',
    read: (h) => h.HIVEL2,
    testValue: 127,
  },
  {
    field: 'VTUNO2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVTUNO2',
    read: (h) => h.VTUNO2,
    testValue: 3,
  },
  {
    field: 'VLOUD2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVLOUD2',
    read: (h) => h.VLOUD2,
    testValue: 8,
  },
  {
    field: 'VFREQ2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVFREQ2',
    read: (h) => h.VFREQ2,
    testValue: 4,
  },
  {
    field: 'VPANO2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVPANO2',
    read: (h) => h.VPANO2,
    testValue: 10,
  },
  {
    field: 'ZPLAY2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeZPLAY2',
    read: (h) => h.ZPLAY2,
    testValue: 1,
  },
  {
    field: 'LVXF2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLVXF2',
    read: (h) => h.LVXF2,
    testValue: 0,
    skip: 'Internal velocity crossfade',
  },
  {
    field: 'HVXF2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHVXF2',
    read: (h) => h.HVXF2,
    testValue: 0,
    skip: 'Internal velocity crossfade',
  },
  {
    field: 'SBADD2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeSBADD2',
    read: (h) => h.SBADD2,
    testValue: 0,
    skip: 'Internal sample block address',
  },
  // --- Zone 3 ---
  {
    field: 'SNAME3',
    type: 'string',
    writeFn: 'KeygroupHeader_writeSNAME3',
    read: (h) => h.SNAME3,
    testValue: 'FIELDTEST3  ',
  },
  {
    field: 'LOVEL3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLOVEL3',
    read: (h) => h.LOVEL3,
    testValue: 0,
  },
  {
    field: 'HIVEL3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHIVEL3',
    read: (h) => h.HIVEL3,
    testValue: 127,
  },
  {
    field: 'VTUNO3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVTUNO3',
    read: (h) => h.VTUNO3,
    testValue: 2,
  },
  {
    field: 'VLOUD3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVLOUD3',
    read: (h) => h.VLOUD3,
    testValue: 5,
  },
  {
    field: 'VFREQ3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVFREQ3',
    read: (h) => h.VFREQ3,
    testValue: 3,
  },
  {
    field: 'VPANO3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVPANO3',
    read: (h) => h.VPANO3,
    testValue: 8,
  },
  {
    field: 'ZPLAY3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeZPLAY3',
    read: (h) => h.ZPLAY3,
    testValue: 3,
  },
  {
    field: 'LVXF3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLVXF3',
    read: (h) => h.LVXF3,
    testValue: 0,
    skip: 'Internal velocity crossfade',
  },
  {
    field: 'HVXF3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHVXF3',
    read: (h) => h.HVXF3,
    testValue: 0,
    skip: 'Internal velocity crossfade',
  },
  {
    field: 'SBADD3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeSBADD3',
    read: (h) => h.SBADD3,
    testValue: 0,
    skip: 'Internal sample block address',
  },
  // --- Zone 4 ---
  {
    field: 'SNAME4',
    type: 'string',
    writeFn: 'KeygroupHeader_writeSNAME4',
    read: (h) => h.SNAME4,
    testValue: 'FIELDTEST4  ',
  },
  {
    field: 'LOVEL4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLOVEL4',
    read: (h) => h.LOVEL4,
    testValue: 0,
  },
  {
    field: 'HIVEL4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHIVEL4',
    read: (h) => h.HIVEL4,
    testValue: 127,
  },
  {
    field: 'VTUNO4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVTUNO4',
    read: (h) => h.VTUNO4,
    testValue: 1,
  },
  {
    field: 'VLOUD4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVLOUD4',
    read: (h) => h.VLOUD4,
    testValue: 3,
  },
  {
    field: 'VFREQ4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVFREQ4',
    read: (h) => h.VFREQ4,
    testValue: 2,
  },
  {
    field: 'VPANO4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVPANO4',
    read: (h) => h.VPANO4,
    testValue: 5,
  },
  {
    field: 'ZPLAY4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeZPLAY4',
    read: (h) => h.ZPLAY4,
    testValue: 0,
  },
  {
    field: 'LVXF4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLVXF4',
    read: (h) => h.LVXF4,
    testValue: 0,
    skip: 'Internal velocity crossfade',
  },
  {
    field: 'HVXF4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeHVXF4',
    read: (h) => h.HVXF4,
    testValue: 0,
    skip: 'Internal velocity crossfade',
  },
  {
    field: 'SBADD4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeSBADD4',
    read: (h) => h.SBADD4,
    testValue: 0,
    skip: 'Internal sample block address',
  },
  // --- Non-zone fields ---
  {
    field: 'KBEAT',
    type: 'number',
    writeFn: 'KeygroupHeader_writeKBEAT',
    read: (h) => h.KBEAT,
    testValue: 10,
  },
  {
    field: 'AHOLD',
    type: 'number',
    writeFn: 'KeygroupHeader_writeAHOLD',
    read: (h) => h.AHOLD,
    testValue: 1,
  },
  {
    field: 'CP1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeCP1',
    read: (h) => h.CP1,
    testValue: 1,
  },
  {
    field: 'CP2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeCP2',
    read: (h) => h.CP2,
    testValue: 1,
  },
  {
    field: 'CP3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeCP3',
    read: (h) => h.CP3,
    testValue: 0,
  },
  {
    field: 'CP4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeCP4',
    read: (h) => h.CP4,
    testValue: 0,
  },
  {
    field: 'VZOUT1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVZOUT1',
    read: (h) => h.VZOUT1,
    testValue: 2,
  },
  {
    field: 'VZOUT2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVZOUT2',
    read: (h) => h.VZOUT2,
    testValue: 1,
  },
  {
    field: 'VZOUT3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVZOUT3',
    read: (h) => h.VZOUT3,
    testValue: 3,
  },
  {
    field: 'VZOUT4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVZOUT4',
    read: (h) => h.VZOUT4,
    testValue: 0,
  },
  {
    field: 'VSS1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVSS1',
    read: (h) => h.VSS1,
    testValue: 100,
  },
  {
    field: 'VSS2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVSS2',
    read: (h) => h.VSS2,
    testValue: 50,
  },
  {
    field: 'VSS3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVSS3',
    read: (h) => h.VSS3,
    testValue: 75,
  },
  {
    field: 'VSS4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeVSS4',
    read: (h) => h.VSS4,
    testValue: 25,
  },
  {
    field: 'KV_LO',
    type: 'number',
    writeFn: 'KeygroupHeader_writeKV_LO',
    read: (h) => h.KV_LO,
    testValue: 5,
  },
  {
    field: 'FILQ',
    type: 'number',
    writeFn: 'KeygroupHeader_writeFILQ',
    read: (h) => h.FILQ,
    testValue: 8,
  },
  {
    field: 'L_PTCH',
    type: 'number',
    writeFn: 'KeygroupHeader_writeL_PTCH',
    read: (h) => h.L_PTCH,
    testValue: 12,
  },
  {
    field: 'MODVFILT1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeMODVFILT1',
    read: (h) => h.MODVFILT1,
    testValue: 20,
  },
  {
    field: 'MODVFILT2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeMODVFILT2',
    read: (h) => h.MODVFILT2,
    testValue: 15,
  },
  {
    field: 'MODVFILT3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeMODVFILT3',
    read: (h) => h.MODVFILT3,
    testValue: 10,
  },
  {
    field: 'MODVPITCH',
    type: 'number',
    writeFn: 'KeygroupHeader_writeMODVPITCH',
    read: (h) => h.MODVPITCH,
    testValue: 15,
  },
  {
    field: 'MODVAMP3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeMODVAMP3',
    read: (h) => h.MODVAMP3,
    testValue: 10,
  },
  {
    field: 'ENV2L1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV2L1',
    read: (h) => h.ENV2L1,
    testValue: 50,
  },
  {
    field: 'ENV2R2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV2R2',
    read: (h) => h.ENV2R2,
    testValue: 30,
  },
  {
    field: 'ENV2L2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV2L2',
    read: (h) => h.ENV2L2,
    testValue: 40,
  },
  {
    field: 'ENV2L4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV2L4',
    read: (h) => h.ENV2L4,
    testValue: 35,
  },
  {
    field: 'KGMUTE',
    type: 'number',
    writeFn: 'KeygroupHeader_writeKGMUTE',
    read: (h) => h.KGMUTE,
    testValue: 5,
  },
  {
    field: 'PFXCHAN',
    type: 'number',
    writeFn: 'KeygroupHeader_writePFXCHAN',
    read: (h) => h.PFXCHAN,
    testValue: 2,
  },
  {
    field: 'PFXSLEV',
    type: 'number',
    writeFn: 'KeygroupHeader_writePFXSLEV',
    read: (h) => h.PFXSLEV,
    testValue: 50,
  },
  {
    field: 'Reserved_1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeReserved_1',
    read: (h) => h.Reserved_1,
    testValue: 0,
    skip: 'Reserved field',
  },
  {
    field: 'LSI2_ON',
    type: 'number',
    writeFn: 'KeygroupHeader_writeLSI2_ON',
    read: (h) => h.LSI2_ON,
    testValue: 1,
  },
  {
    field: 'FLT2GAIN',
    type: 'number',
    writeFn: 'KeygroupHeader_writeFLT2GAIN',
    read: (h) => h.FLT2GAIN,
    testValue: 6,
  },
  {
    field: 'FLT2MODE',
    type: 'number',
    writeFn: 'KeygroupHeader_writeFLT2MODE',
    read: (h) => h.FLT2MODE,
    testValue: 1,
  },
  {
    field: 'FLT2Q',
    type: 'number',
    writeFn: 'KeygroupHeader_writeFLT2Q',
    read: (h) => h.FLT2Q,
    testValue: 8,
  },
  {
    field: 'TONEFREQ',
    type: 'number',
    writeFn: 'KeygroupHeader_writeTONEFREQ',
    read: (h) => h.TONEFREQ,
    testValue: 50,
  },
  {
    field: 'TONESLOP',
    type: 'number',
    writeFn: 'KeygroupHeader_writeTONESLOP',
    read: (h) => h.TONESLOP,
    testValue: 25,
  },
  {
    field: 'MODVFLT2_1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeMODVFLT2_1',
    read: (h) => h.MODVFLT2_1,
    testValue: 15,
  },
  {
    field: 'MODVFLT2_2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeMODVFLT2_2',
    read: (h) => h.MODVFLT2_2,
    testValue: 10,
  },
  {
    field: 'MODVFLT2_3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeMODVFLT2_3',
    read: (h) => h.MODVFLT2_3,
    testValue: 5,
  },
  {
    field: 'FIL2FR',
    type: 'number',
    writeFn: 'KeygroupHeader_writeFIL2FR',
    read: (h) => h.FIL2FR,
    testValue: 45,
  },
  {
    field: 'K_FRQ2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeK_FRQ2',
    read: (h) => h.K_FRQ2,
    testValue: 20,
  },
  {
    field: 'ATTAK3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeATTAK3',
    read: (h) => h.ATTAK3,
    testValue: 25,
  },
  {
    field: 'ENV3L1',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV3L1',
    read: (h) => h.ENV3L1,
    testValue: 60,
  },
  {
    field: 'ENV3R2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV3R2',
    read: (h) => h.ENV3R2,
    testValue: 35,
  },
  {
    field: 'ENV3L2',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV3L2',
    read: (h) => h.ENV3L2,
    testValue: 45,
  },
  {
    field: 'ENV3R3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV3R3',
    read: (h) => h.ENV3R3,
    testValue: 20,
  },
  {
    field: 'ENV3L3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV3L3',
    read: (h) => h.ENV3L3,
    testValue: 55,
  },
  {
    field: 'ENV3R4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV3R4',
    read: (h) => h.ENV3R4,
    testValue: 15,
  },
  {
    field: 'ENV3L4',
    type: 'number',
    writeFn: 'KeygroupHeader_writeENV3L4',
    read: (h) => h.ENV3L4,
    testValue: 40,
  },
  {
    field: 'V_ATT3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_ATT3',
    read: (h) => h.V_ATT3,
    testValue: 10,
  },
  {
    field: 'V_REL3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_REL3',
    read: (h) => h.V_REL3,
    testValue: 8,
  },
  {
    field: 'O_REL3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeO_REL3',
    read: (h) => h.O_REL3,
    testValue: 4,
  },
  {
    field: 'K_DAR3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeK_DAR3',
    read: (h) => h.K_DAR3,
    testValue: 6,
  },
  {
    field: 'V_ENV3',
    type: 'number',
    writeFn: 'KeygroupHeader_writeV_ENV3',
    read: (h) => h.V_ENV3,
    testValue: 15,
  },
  {
    field: 'KFXCHAN',
    type: 'number',
    writeFn: 'KeygroupHeader_writeKFXCHAN',
    read: (h) => h.KFXCHAN,
    testValue: 1,
    skip: 'Keygroup FX override — device does not persist writes, causes subsequent timeouts',
  },
  {
    field: 'KFXSLEV',
    type: 'number',
    writeFn: 'KeygroupHeader_writeKFXSLEV',
    read: (h) => h.KFXSLEV,
    testValue: 40,
    skip: 'Keygroup FX send level — depends on KFXCHAN which causes timeouts',
  },
];
