import type { SampleHeader } from '@audiocontrol/sampler-devices/s3k';
import type { FieldSpec } from '@/node/lib/field-specs-program.js';

export const SAMPLE_FIELD_SPECS: FieldSpec<SampleHeader>[] = [
  {
    field: 'SHIDENT',
    type: 'number',
    writeFn: 'SampleHeader_writeSHIDENT',
    read: (h) => h.SHIDENT,
    testValue: 0,
    skip: 'Block identifier, internal',
  },
  {
    field: 'SBANDW',
    type: 'number',
    writeFn: 'SampleHeader_writeSBANDW',
    read: (h) => h.SBANDW,
    testValue: 1,
  },
  {
    field: 'SPITCH',
    type: 'number',
    writeFn: 'SampleHeader_writeSPITCH',
    read: (h) => h.SPITCH,
    testValue: 60,
  },
  {
    field: 'SHNAME',
    type: 'string',
    writeFn: 'SampleHeader_writeSHNAME',
    read: (h) => h.SHNAME,
    testValue: 'FIELDTEST   ',
  },
  {
    field: 'SSRVLD',
    type: 'number',
    writeFn: 'SampleHeader_writeSSRVLD',
    read: (h) => h.SSRVLD,
    testValue: 0,
    skip: 'Sample rate validity flag (0=invalid, 128=valid) — writing may corrupt sample playback',
  },
  {
    field: 'SLOOPS',
    type: 'number',
    writeFn: 'SampleHeader_writeSLOOPS',
    read: (h) => h.SLOOPS,
    testValue: 0,
    skip: 'Loop count managed by device based on loop point data',
  },
  {
    field: 'SALOOP',
    type: 'number',
    writeFn: 'SampleHeader_writeSALOOP',
    read: (h) => h.SALOOP,
    testValue: 0,
    skip: 'First active loop — internal use',
  },
  {
    field: 'SHLOOP',
    type: 'number',
    writeFn: 'SampleHeader_writeSHLOOP',
    read: (h) => h.SHLOOP,
    testValue: 0,
    skip: 'Highest loop — internal use',
  },
  {
    field: 'SPTYPE',
    type: 'number',
    writeFn: 'SampleHeader_writeSPTYPE',
    read: (h) => h.SPTYPE,
    testValue: 1,
  },
  {
    field: 'STUNO',
    type: 'number',
    writeFn: 'SampleHeader_writeSTUNO',
    read: (h) => h.STUNO,
    testValue: 5,
  },
  {
    field: 'SLOCAT',
    type: 'number',
    writeFn: 'SampleHeader_writeSLOCAT',
    read: (h) => h.SLOCAT,
    testValue: 0,
    skip: 'Internal memory location',
  },
  {
    field: 'SLNGTH',
    type: 'number',
    writeFn: 'SampleHeader_writeSLNGTH',
    read: (h) => h.SLNGTH,
    testValue: 0,
    skip: 'Internal sample length',
  },
  {
    field: 'SSTART',
    type: 'number',
    writeFn: 'SampleHeader_writeSSTART',
    read: (h) => h.SSTART,
    testValue: 100,
  },
  {
    field: 'SMPEND',
    type: 'number',
    writeFn: 'SampleHeader_writeSMPEND',
    read: (h) => h.SMPEND,
    testValue: 0,
    skip: 'Internal sample end point',
  },
  {
    field: 'LOOPAT1',
    type: 'number',
    writeFn: 'SampleHeader_writeLOOPAT1',
    read: (h) => h.LOOPAT1,
    testValue: 50,
  },
  {
    field: 'LLNGTH1',
    type: 'number',
    writeFn: 'SampleHeader_writeLLNGTH1',
    read: (h) => h.LLNGTH1,
    testValue: 0,
    skip: 'Loop length (6 bytes) — device-managed based on loop points and sample length',
  },
  {
    field: 'LDWELL1',
    type: 'number',
    writeFn: 'SampleHeader_writeLDWELL1',
    read: (h) => h.LDWELL1,
    testValue: 500,
  },
  {
    field: 'LOOPAT2',
    type: 'number',
    writeFn: 'SampleHeader_writeLOOPAT2',
    read: (h) => h.LOOPAT2,
    testValue: 100,
  },
  {
    field: 'LLNGTH2',
    type: 'number',
    writeFn: 'SampleHeader_writeLLNGTH2',
    read: (h) => h.LLNGTH2,
    testValue: 150,
  },
  {
    field: 'LDWELL2',
    type: 'number',
    writeFn: 'SampleHeader_writeLDWELL2',
    read: (h) => h.LDWELL2,
    testValue: 5,
  },
  {
    field: 'LOOPAT3',
    type: 'number',
    writeFn: 'SampleHeader_writeLOOPAT3',
    read: (h) => h.LOOPAT3,
    testValue: 200,
  },
  {
    field: 'LLNGTH3',
    type: 'number',
    writeFn: 'SampleHeader_writeLLNGTH3',
    read: (h) => h.LLNGTH3,
    testValue: 100,
  },
  {
    field: 'LDWELL3',
    type: 'number',
    writeFn: 'SampleHeader_writeLDWELL3',
    read: (h) => h.LDWELL3,
    testValue: 8,
  },
  {
    field: 'LOOPAT4',
    type: 'number',
    writeFn: 'SampleHeader_writeLOOPAT4',
    read: (h) => h.LOOPAT4,
    testValue: 50,
  },
  {
    field: 'LLNGTH4',
    type: 'number',
    writeFn: 'SampleHeader_writeLLNGTH4',
    read: (h) => h.LLNGTH4,
    testValue: 75,
  },
  {
    field: 'LDWELL4',
    type: 'number',
    writeFn: 'SampleHeader_writeLDWELL4',
    read: (h) => h.LDWELL4,
    testValue: 3,
  },
  {
    field: 'SLXY1',
    type: 'number',
    writeFn: 'SampleHeader_writeSLXY1',
    read: (h) => h.SLXY1,
    testValue: 0,
    skip: 'Relative loop factors (12 bytes) — complex multi-byte field, device-managed',
  },
  {
    field: 'SLXY2',
    type: 'number',
    writeFn: 'SampleHeader_writeSLXY2',
    read: (h) => h.SLXY2,
    testValue: 20,
  },
  {
    field: 'SLXY3',
    type: 'number',
    writeFn: 'SampleHeader_writeSLXY3',
    read: (h) => h.SLXY3,
    testValue: 30,
  },
  {
    field: 'SLXY4',
    type: 'number',
    writeFn: 'SampleHeader_writeSLXY4',
    read: (h) => h.SLXY4,
    testValue: 40,
  },
  {
    field: 'SSPARE',
    type: 'number',
    writeFn: 'SampleHeader_writeSSPARE',
    read: (h) => h.SSPARE,
    testValue: 1,
  },
  {
    field: 'SWCOMM',
    type: 'number',
    writeFn: 'SampleHeader_writeSWCOMM',
    read: (h) => h.SWCOMM,
    testValue: 1,
  },
  {
    field: 'SSPAIR',
    type: 'number',
    writeFn: 'SampleHeader_writeSSPAIR',
    read: (h) => h.SSPAIR,
    testValue: 0,
    skip: 'Address of stereo partner — internal use',
  },
  {
    field: 'SSRATE',
    type: 'number',
    writeFn: 'SampleHeader_writeSSRATE',
    read: (h) => h.SSRATE,
    testValue: 0,
    skip: 'Writing sample rate may corrupt playback',
  },
  {
    field: 'SHLTO',
    type: 'number',
    writeFn: 'SampleHeader_writeSHLTO',
    read: (h) => h.SHLTO,
    testValue: 5,
  },
];
