import type { ProgramHeader } from '@audiocontrol/sampler-devices/s3k';

export interface FieldSpec<H> {
  field: string;
  type: 'number' | 'string';
  writeFn: string;
  read: (h: H) => number | string;
  testValue: number | string;
  skip?: string;
}

export const PROGRAM_FIELD_SPECS: FieldSpec<ProgramHeader>[] = [
  {
    field: 'KGRP1',
    type: 'number',
    writeFn: 'ProgramHeader_writeKGRP1',
    read: (h) => h.KGRP1,
    testValue: 0,
    skip: 'Internal block address, writing may corrupt program',
  },
  {
    field: 'PRNAME',
    type: 'string',
    writeFn: 'ProgramHeader_writePRNAME',
    read: (h) => h.PRNAME,
    testValue: 'FIELDTEST   ',
  },
  {
    field: 'PRGNUM',
    type: 'number',
    writeFn: 'ProgramHeader_writePRGNUM',
    read: (h) => h.PRGNUM,
    testValue: 42,
  },
  {
    field: 'PMCHAN',
    type: 'number',
    writeFn: 'ProgramHeader_writePMCHAN',
    read: (h) => h.PMCHAN,
    testValue: 5,
  },
  {
    field: 'POLYPH',
    type: 'number',
    writeFn: 'ProgramHeader_writePOLYPH',
    read: (h) => h.POLYPH,
    testValue: 15,
  },
  {
    field: 'PRIORT',
    type: 'number',
    writeFn: 'ProgramHeader_writePRIORT',
    read: (h) => h.PRIORT,
    testValue: 2,
  },
  {
    field: 'PLAYLO',
    type: 'number',
    writeFn: 'ProgramHeader_writePLAYLO',
    read: (h) => h.PLAYLO,
    testValue: 36,
  },
  {
    field: 'PLAYHI',
    type: 'number',
    writeFn: 'ProgramHeader_writePLAYHI',
    read: (h) => h.PLAYHI,
    testValue: 96,
  },
  {
    field: 'OSHIFT',
    type: 'number',
    writeFn: 'ProgramHeader_writeOSHIFT',
    read: (h) => h.OSHIFT,
    testValue: 12,
  },
  {
    field: 'OUTPUT',
    type: 'number',
    writeFn: 'ProgramHeader_writeOUTPUT',
    read: (h) => h.OUTPUT,
    testValue: 1,
  },
  {
    field: 'STEREO',
    type: 'number',
    writeFn: 'ProgramHeader_writeSTEREO',
    read: (h) => h.STEREO,
    testValue: 50,
  },
  {
    field: 'PANPOS',
    type: 'number',
    writeFn: 'ProgramHeader_writePANPOS',
    read: (h) => h.PANPOS,
    testValue: 25,
  },
  {
    field: 'PRLOUD',
    type: 'number',
    writeFn: 'ProgramHeader_writePRLOUD',
    read: (h) => h.PRLOUD,
    testValue: 75,
  },
  {
    field: 'V_LOUD',
    type: 'number',
    writeFn: 'ProgramHeader_writeV_LOUD',
    read: (h) => h.V_LOUD,
    testValue: 25,
  },
  {
    field: 'K_LOUD',
    type: 'number',
    writeFn: 'ProgramHeader_writeK_LOUD',
    read: (h) => h.K_LOUD,
    testValue: 10,
  },
  {
    field: 'P_LOUD',
    type: 'number',
    writeFn: 'ProgramHeader_writeP_LOUD',
    read: (h) => h.P_LOUD,
    testValue: 10,
  },
  {
    field: 'PANRAT',
    type: 'number',
    writeFn: 'ProgramHeader_writePANRAT',
    read: (h) => h.PANRAT,
    testValue: 50,
  },
  {
    field: 'PANDEP',
    type: 'number',
    writeFn: 'ProgramHeader_writePANDEP',
    read: (h) => h.PANDEP,
    testValue: 30,
  },
  {
    field: 'PANDEL',
    type: 'number',
    writeFn: 'ProgramHeader_writePANDEL',
    read: (h) => h.PANDEL,
    testValue: 20,
  },
  {
    field: 'K_PANP',
    type: 'number',
    writeFn: 'ProgramHeader_writeK_PANP',
    read: (h) => h.K_PANP,
    testValue: 10,
  },
  {
    field: 'LFORAT',
    type: 'number',
    writeFn: 'ProgramHeader_writeLFORAT',
    read: (h) => h.LFORAT,
    testValue: 40,
  },
  {
    field: 'LFODEP',
    type: 'number',
    writeFn: 'ProgramHeader_writeLFODEP',
    read: (h) => h.LFODEP,
    testValue: 30,
  },
  {
    field: 'LFODEL',
    type: 'number',
    writeFn: 'ProgramHeader_writeLFODEL',
    read: (h) => h.LFODEL,
    testValue: 25,
  },
  {
    field: 'MWLDEP',
    type: 'number',
    writeFn: 'ProgramHeader_writeMWLDEP',
    read: (h) => h.MWLDEP,
    testValue: 40,
  },
  {
    field: 'PRSDEP',
    type: 'number',
    writeFn: 'ProgramHeader_writePRSDEP',
    read: (h) => h.PRSDEP,
    testValue: 30,
  },
  {
    field: 'VELDEP',
    type: 'number',
    writeFn: 'ProgramHeader_writeVELDEP',
    read: (h) => h.VELDEP,
    testValue: 20,
  },
  {
    field: 'B_PTCH',
    type: 'number',
    writeFn: 'ProgramHeader_writeB_PTCH',
    read: (h) => h.B_PTCH,
    testValue: 7,
  },
  {
    field: 'P_PTCH',
    type: 'number',
    writeFn: 'ProgramHeader_writeP_PTCH',
    read: (h) => h.P_PTCH,
    testValue: 5,
  },
  {
    field: 'KXFADE',
    type: 'number',
    writeFn: 'ProgramHeader_writeKXFADE',
    read: (h) => h.KXFADE,
    testValue: 1,
  },
  {
    field: 'GROUPS',
    type: 'number',
    writeFn: 'ProgramHeader_writeGROUPS',
    read: (h) => h.GROUPS,
    testValue: 0,
    skip: 'Keygroup count managed by device via KDATA/DELK',
  },
  {
    field: 'TPNUM',
    type: 'number',
    writeFn: 'ProgramHeader_writeTPNUM',
    read: (h) => h.TPNUM,
    testValue: 0,
    skip: 'Internal use',
  },
  {
    field: 'TEMPER',
    type: 'string',
    writeFn: 'ProgramHeader_writeTEMPER',
    read: (h) => h.TEMPER,
    testValue: 'TESTTEMPER  ',
  },
  {
    field: 'ECHOUT',
    type: 'number',
    writeFn: 'ProgramHeader_writeECHOUT',
    read: (h) => h.ECHOUT,
    testValue: 1,
  },
  {
    field: 'MW_PAN',
    type: 'number',
    writeFn: 'ProgramHeader_writeMW_PAN',
    read: (h) => h.MW_PAN,
    testValue: 1,
  },
  {
    field: 'COHERE',
    type: 'number',
    writeFn: 'ProgramHeader_writeCOHERE',
    read: (h) => h.COHERE,
    testValue: 1,
  },
  {
    field: 'DESYNC',
    type: 'number',
    writeFn: 'ProgramHeader_writeDESYNC',
    read: (h) => h.DESYNC,
    testValue: 1,
  },
  {
    field: 'PLAW',
    type: 'number',
    writeFn: 'ProgramHeader_writePLAW',
    read: (h) => h.PLAW,
    testValue: 1,
  },
  {
    field: 'VASSOQ',
    type: 'number',
    writeFn: 'ProgramHeader_writeVASSOQ',
    read: (h) => h.VASSOQ,
    testValue: 1,
  },
  {
    field: 'SPLOUD',
    type: 'number',
    writeFn: 'ProgramHeader_writeSPLOUD',
    read: (h) => h.SPLOUD,
    testValue: 30,
  },
  {
    field: 'SPATT',
    type: 'number',
    writeFn: 'ProgramHeader_writeSPATT',
    read: (h) => h.SPATT,
    testValue: 20,
  },
  {
    field: 'SPFILT',
    type: 'number',
    writeFn: 'ProgramHeader_writeSPFILT',
    read: (h) => h.SPFILT,
    testValue: 25,
  },
  {
    field: 'PTUNO',
    type: 'number',
    writeFn: 'ProgramHeader_writePTUNO',
    read: (h) => h.PTUNO,
    testValue: 10,
  },
  {
    field: 'K_LRAT',
    type: 'number',
    writeFn: 'ProgramHeader_writeK_LRAT',
    read: (h) => h.K_LRAT,
    testValue: 15,
  },
  {
    field: 'K_LDEP',
    type: 'number',
    writeFn: 'ProgramHeader_writeK_LDEP',
    read: (h) => h.K_LDEP,
    testValue: 10,
  },
  {
    field: 'K_LDEL',
    type: 'number',
    writeFn: 'ProgramHeader_writeK_LDEL',
    read: (h) => h.K_LDEL,
    testValue: 10,
  },
  {
    field: 'VOSCL',
    type: 'number',
    writeFn: 'ProgramHeader_writeVOSCL',
    read: (h) => h.VOSCL,
    testValue: 50,
  },
  {
    field: 'VSSCL',
    type: 'number',
    writeFn: 'ProgramHeader_writeVSSCL',
    read: (h) => h.VSSCL,
    testValue: 30,
  },
  {
    field: 'LEGATO',
    type: 'number',
    writeFn: 'ProgramHeader_writeLEGATO',
    read: (h) => h.LEGATO,
    testValue: 1,
  },
  {
    field: 'B_PTCHD',
    type: 'number',
    writeFn: 'ProgramHeader_writeB_PTCHD',
    read: (h) => h.B_PTCHD,
    testValue: 5,
  },
  {
    field: 'B_MODE',
    type: 'number',
    writeFn: 'ProgramHeader_writeB_MODE',
    read: (h) => h.B_MODE,
    testValue: 1,
  },
  {
    field: 'TRANSPOSE',
    type: 'number',
    writeFn: 'ProgramHeader_writeTRANSPOSE',
    read: (h) => h.TRANSPOSE,
    testValue: 5,
  },
  {
    field: 'MODSPAN1',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSPAN1',
    read: (h) => h.MODSPAN1,
    testValue: 3,
  },
  {
    field: 'MODSPAN2',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSPAN2',
    read: (h) => h.MODSPAN2,
    testValue: 2,
  },
  {
    field: 'MODSPAN3',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSPAN3',
    read: (h) => h.MODSPAN3,
    testValue: 1,
  },
  {
    field: 'MODSAMP1',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSAMP1',
    read: (h) => h.MODSAMP1,
    testValue: 3,
  },
  {
    field: 'MODSAMP2',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSAMP2',
    read: (h) => h.MODSAMP2,
    testValue: 2,
  },
  {
    field: 'MODSLFOT',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSLFOT',
    read: (h) => h.MODSLFOT,
    testValue: 2,
  },
  {
    field: 'MODSLFOL',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSLFOL',
    read: (h) => h.MODSLFOL,
    testValue: 3,
  },
  {
    field: 'MODSLFOD',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSLFOD',
    read: (h) => h.MODSLFOD,
    testValue: 1,
  },
  {
    field: 'MODSFILT1',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSFILT1',
    read: (h) => h.MODSFILT1,
    testValue: 3,
  },
  {
    field: 'MODSFILT2',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSFILT2',
    read: (h) => h.MODSFILT2,
    testValue: 2,
  },
  {
    field: 'MODSFILT3',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSFILT3',
    read: (h) => h.MODSFILT3,
    testValue: 1,
  },
  {
    field: 'MODSPITCH',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSPITCH',
    read: (h) => h.MODSPITCH,
    testValue: 2,
  },
  {
    field: 'MODSAMP3',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSAMP3',
    read: (h) => h.MODSAMP3,
    testValue: 1,
  },
  {
    field: 'MODVPAN1',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODVPAN1',
    read: (h) => h.MODVPAN1,
    testValue: 25,
  },
  {
    field: 'MODVPAN2',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODVPAN2',
    read: (h) => h.MODVPAN2,
    testValue: 15,
  },
  {
    field: 'MODVPAN3',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODVPAN3',
    read: (h) => h.MODVPAN3,
    testValue: 10,
  },
  {
    field: 'MODVAMP1',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODVAMP1',
    read: (h) => h.MODVAMP1,
    testValue: 20,
  },
  {
    field: 'MODVAMP2',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODVAMP2',
    read: (h) => h.MODVAMP2,
    testValue: 15,
  },
  {
    field: 'MODVLFOR',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODVLFOR',
    read: (h) => h.MODVLFOR,
    testValue: 30,
  },
  {
    field: 'MODVLVOL',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODVLVOL',
    read: (h) => h.MODVLVOL,
    testValue: 20,
  },
  {
    field: 'MODVLFOD',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODVLFOD',
    read: (h) => h.MODVLFOD,
    testValue: 10,
  },
  {
    field: 'LFO1WAVE',
    type: 'number',
    writeFn: 'ProgramHeader_writeLFO1WAVE',
    read: (h) => h.LFO1WAVE,
    testValue: 2,
  },
  {
    field: 'LFO2WAVE',
    type: 'number',
    writeFn: 'ProgramHeader_writeLFO2WAVE',
    read: (h) => h.LFO2WAVE,
    testValue: 3,
  },
  {
    field: 'MODSLFLT2_1',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSLFLT2_1',
    read: (h) => h.MODSLFLT2_1,
    testValue: 2,
  },
  {
    field: 'MODSLFLT2_2',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSLFLT2_2',
    read: (h) => h.MODSLFLT2_2,
    testValue: 1,
  },
  {
    field: 'MODSLFLT2_3',
    type: 'number',
    writeFn: 'ProgramHeader_writeMODSLFLT2_3',
    read: (h) => h.MODSLFLT2_3,
    testValue: 3,
  },
  {
    field: 'LFO2TRIG',
    type: 'number',
    writeFn: 'ProgramHeader_writeLFO2TRIG',
    read: (h) => h.LFO2TRIG,
    testValue: 1,
  },
  {
    field: 'RESERVED_1',
    type: 'number',
    writeFn: 'ProgramHeader_writeRESERVED_1',
    read: (h) => h.RESERVED_1,
    testValue: 0,
    skip: 'Reserved field',
  },
  {
    field: 'PORTIME',
    type: 'number',
    writeFn: 'ProgramHeader_writePORTIME',
    read: (h) => h.PORTIME,
    testValue: 40,
  },
  {
    field: 'PORTYPE',
    type: 'number',
    writeFn: 'ProgramHeader_writePORTYPE',
    read: (h) => h.PORTYPE,
    testValue: 1,
  },
  {
    field: 'PORTEN',
    type: 'number',
    writeFn: 'ProgramHeader_writePORTEN',
    read: (h) => h.PORTEN,
    testValue: 1,
  },
  {
    field: 'PFXCHAN',
    type: 'number',
    writeFn: 'ProgramHeader_writePFXCHAN',
    read: (h) => h.PFXCHAN,
    testValue: 2,
  },
];
