import type { Caption } from '@/types.js';

/**
 * Format milliseconds as MM:SS timestamp string.
 */
const formatTimestamp = (ms: number): string => {
  const totalSeconds = Math.floor(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
};

/**
 * Escape a string for safe inclusion in YAML. Always double-quotes for consistency.
 */
const yamlEscapeString = (text: string): string => {
  const escaped = text.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
};

/**
 * Generate a YAML file describing timed captions for text overlay compositing.
 */
export const generateCaptionsYaml = (
  scenarioName: string,
  captions: ReadonlyArray<Caption>,
  videoDurationMs: number,
): string => {
  const lines: string[] = [];
  lines.push('# Generated by video-control');
  lines.push(`scenario: ${scenarioName}`);
  lines.push(`duration_ms: ${videoDurationMs}`);
  lines.push('captions:');

  for (const caption of captions) {
    lines.push(`  - text: ${yamlEscapeString(caption.text)}`);
    lines.push(`    timestamp_ms: ${caption.timestampMs}`);
    lines.push(`    duration_ms: ${caption.durationMs}`);
    lines.push(`    type: ${caption.type}`);
  }

  return lines.join('\n') + '\n';
};

/**
 * Wrap text at approximately maxWidth characters, preserving word boundaries.
 * Returns an array of lines.
 */
const wrapText = (text: string, maxWidth: number): string[] => {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if (currentLine.length === 0) {
      currentLine = word;
    } else if (currentLine.length + 1 + word.length <= maxWidth) {
      currentLine += ' ' + word;
    } else {
      lines.push(currentLine);
      currentLine = word;
    }
  }
  if (currentLine.length > 0) {
    lines.push(currentLine);
  }
  return lines;
};

/**
 * Format a scenario name into a human-readable title.
 * e.g. "s3k-zone-editor" -> "S3k Zone Editor"
 */
const formatTitle = (scenarioName: string): string => {
  return scenarioName
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

/**
 * Generate a plain-text voiceover script with timestamps for a narrator to read.
 */
export const generateVoScript = (
  scenarioName: string,
  captions: ReadonlyArray<Caption>,
  videoDurationMs: number,
): string => {
  const title = `Voiceover Script: ${formatTitle(scenarioName)}`;
  const separator = '='.repeat(title.length);
  const lines: string[] = [];
  lines.push(title);
  lines.push(separator);
  lines.push('');

  const LINE_WIDTH = 70;
  const INDENT = '        '; // 8 spaces to align with content after [MM:SS]

  for (const caption of captions) {
    const timestamp = formatTimestamp(caption.timestampMs);
    const prefix = `[${timestamp}] `;
    const wrapped = wrapText(caption.text, LINE_WIDTH - prefix.length);

    if (wrapped.length > 0) {
      lines.push(`${prefix}${wrapped[0]}`);
      for (let i = 1; i < wrapped.length; i++) {
        lines.push(`${INDENT}${wrapped[i]}`);
      }
    }
    lines.push('');
  }

  const totalSeconds = (videoDurationMs / 1000).toFixed(1);
  lines.push(`Total duration: ${totalSeconds}s`);
  lines.push('');

  return lines.join('\n');
};
