import type { Caption, CaptionType } from '@/types.js';

/**
 * Format milliseconds as MM:SS timestamp string (for VO scripts).
 */
const formatTimestamp = (ms: number): string => {
  const totalSeconds = Math.floor(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
};

/**
 * Format milliseconds as text-overlay timecode: "M:SS.mmm"
 */
const formatTimecode = (ms: number): string => {
  const totalSeconds = Math.floor(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  const millis = ms % 1000;
  return `${minutes}:${String(seconds).padStart(2, '0')}.${String(millis).padStart(3, '0')}`;
};

/**
 * Escape a string for safe inclusion in YAML. Always double-quotes for consistency.
 */
const yamlEscapeString = (text: string): string => {
  const escaped = text.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
};

/**
 * Map our CaptionType to text-overlay overlay type.
 */
const OVERLAY_TYPE_MAP: Record<CaptionType, string> = {
  title: 'title',
  step: 'lower-third',
  callout: 'callout',
};

/**
 * Generate a YAML file conforming to the @audiocontrol/text-overlay ProjectSchema.
 *
 * The output can be validated and rendered by the text-overlay CLI:
 *   textoverlay validate captions.yaml
 *   textoverlay render captions.yaml --video input.mp4
 */
export const generateCaptionsYaml = (
  scenarioName: string,
  captions: ReadonlyArray<Caption>,
  videoDurationMs: number,
): string => {
  const totalDuration = formatTimecode(videoDurationMs);
  const lines: string[] = [];

  lines.push('# Generated by video-control — conforms to @audiocontrol/text-overlay ProjectSchema');
  lines.push('project:');
  lines.push(`  name: ${yamlEscapeString(scenarioName)}`);
  lines.push('  resolution: [1280, 720]');
  lines.push('  framerate: 30');
  lines.push(`  duration: "${totalDuration}"`);
  lines.push('');
  lines.push('defaults:');
  lines.push('  font: "Inter"');
  lines.push('  transition:');
  lines.push('    in: fade');
  lines.push('    out: fade');
  lines.push('    duration: 0.3');
  lines.push('');
  lines.push('theme:');
  lines.push('  primary: "#3B82F6"');
  lines.push('  secondary: "#1E293B"');
  lines.push('  text: "#F8FAFC"');
  lines.push('  accent: "#F59E0B"');
  lines.push('');
  lines.push('overlays:');

  captions.forEach((caption, index) => {
    const inTime = formatTimecode(caption.timestampMs);
    const outTime = formatTimecode(caption.timestampMs + caption.durationMs);
    const overlayType = OVERLAY_TYPE_MAP[caption.type];

    lines.push(`  - id: "caption-${index}"` );
    lines.push(`    type: ${overlayType}`);
    lines.push(`    text: ${yamlEscapeString(caption.text)}`);
    lines.push(`    in: "${inTime}"`);
    lines.push(`    out: "${outTime}"`);
    lines.push('    position: bottom-center');
  });

  return lines.join('\n') + '\n';
};

/**
 * Wrap text at approximately maxWidth characters, preserving word boundaries.
 * Returns an array of lines.
 */
const wrapText = (text: string, maxWidth: number): string[] => {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if (currentLine.length === 0) {
      currentLine = word;
    } else if (currentLine.length + 1 + word.length <= maxWidth) {
      currentLine += ' ' + word;
    } else {
      lines.push(currentLine);
      currentLine = word;
    }
  }
  if (currentLine.length > 0) {
    lines.push(currentLine);
  }
  return lines;
};

/**
 * Format a scenario name into a human-readable title.
 * e.g. "s3k-zone-editor" -> "S3k Zone Editor"
 */
const formatTitle = (scenarioName: string): string => {
  return scenarioName
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

/**
 * Generate a plain-text voiceover script with timestamps for a narrator to read.
 */
export const generateVoScript = (
  scenarioName: string,
  captions: ReadonlyArray<Caption>,
  videoDurationMs: number,
): string => {
  const title = `Voiceover Script: ${formatTitle(scenarioName)}`;
  const separator = '='.repeat(title.length);
  const lines: string[] = [];
  lines.push(title);
  lines.push(separator);
  lines.push('');

  const LINE_WIDTH = 70;
  const INDENT = '        '; // 8 spaces to align with content after [MM:SS]

  for (const caption of captions) {
    const timestamp = formatTimestamp(caption.timestampMs);
    const prefix = `[${timestamp}] `;
    const wrapped = wrapText(caption.text, LINE_WIDTH - prefix.length);

    if (wrapped.length > 0) {
      lines.push(`${prefix}${wrapped[0]}`);
      for (let i = 1; i < wrapped.length; i++) {
        lines.push(`${INDENT}${wrapped[i]}`);
      }
    }
    lines.push('');
  }

  const totalSeconds = (videoDurationMs / 1000).toFixed(1);
  lines.push(`Total duration: ${totalSeconds}s`);
  lines.push('');

  return lines.join('\n');
};
