FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /analyzer
COPY session-analyzer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY session-analyzer/ .
ENTRYPOINT ["python"]
